<?php

return [
    // Small starter list (expand as needed). No runtime external fetch.
    '10minutemail.com',
    '10minutemail.net',
    'discard.email',
    'discardmail.com',
    'guerrillamail.com',
    'guerrillamail.net',
    'maildrop.cc',
    'mailinator.com',
    'mailnesia.com',
    'mintemail.com',
    'mohmal.com',
    'sharklasers.com',
    'spamgourmet.com',
    'temp-mail.org',
    'tempail.com',
    'tempmail.com',
    'tempmail.net',
    'throwawaymail.com',
    'trashmail.com',
    'yopmail.com',
    'yopmail.net',
    'yopmail.fr',
    'getnada.com',
    'nada.email',
    'fakeinbox.com',
    'inboxkitten.com',
    'emailondeck.com',
    'dispostable.com',
    'mailcatch.com',
];
